### ISSUE TITLE
support block-fusion as default

### ISSUE THREAD

**Issue by AlisaChen98** [microsoft/nnfusion#125]
ETA
* support block-fusion as default
   - [ ] fix memory allocation problem #61
   - [ ] automatic failure check #110 
   - [ ] automatic active block check #50

**Comment by nnfbot** [comment]
Thanks for the report @AlisaChen98! I will look into it ASAP! (I'm a bot).
