### ISSUE TITLE
First iteration Planning

### ISSUE THREAD

**Issue by wenxcs** [microsoft/nnfusion#41]
Bugs/Issues

- [ ] Performance Issue compared to internal repo #23

- [ ] Compile error when set -fkernels_as_files=true in model codegen and build model code in non-root folder #26 

- [ ] Unexpected Constant folder was generated by NNFusion CLI #24 

- [ ] Unexpected exit when codegen #40

Code refactor

Documents

Devops

- [ ] Code guideline

- [ ] New bot to handle issues and more ... #19

Features:

- [ ] Mixed precision and low precision

- [ ] Inference

- [ ] Training

- [ ] CPU/APU

- [ ] Memory

Interops:

- [ ]  Antares

**Comment by xiayuqing0622** [comment]
Thanks for the report @wenxcs! I will look into it ASAP! (I'm a bot).

**Comment by AlisaChen98** [comment]
## Feature

### Mechanism

* support training 
* support low-precision & mixed-precision
* outal kernel tuner integration
* offline inference
* integration with super-scalar

### Refactor/Improvement

* detect unsupported model & ops
* support block-fusion as default
* support reduce-fusion
* sub-graph substitution
* code refactor

### Frontend & Backend support

* support CPU
* support HLSL
* model support(training models & more inference models)

### Documentation

* Docs for dev
* Doc website
